import pandas as pd
import time
import os
import sys

clear =lambda:os.system('cls')

print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
for i in range(101):
    time.sleep(0.05)
    sys.stdout.write("\r\t\t\t\t\t %d %% Loading......." % i)
    sys.stdout.flush()
clear()

#--------------------------------Welcome screen ----------------------
print("\n")
print("\n")
mes1="\n\n\t\t\t\t WELCOME\n\n"
for i in mes1:
    time.sleep(0.05)
    print(i,end=" ")
mes2="\t\t\t\t\t TO \n\n"
for i in mes2:
    time.sleep(0.05)
    print(i,end=" ")
mes3="\t\t\t\t COFFEE SHOP \n\n\n"
for i in mes3:
    time.sleep(0.05)
    print(i,end=" ")
mes4="\t\t\t\t\t MANAGEMENT SYSTEM \n\n"
for i in mes4:
    time.sleep(0.01)
    print(i,end=" ")
time.sleep(5.0)   
clear()   
#------------------------------- Main Menu  --------------------------
def menu():
        clear()
        print()
        time.sleep(0.05)
        print("======================================")
        time.sleep(0.5)
        print("         Welcome to Coffee Shop       ")
        time.sleep(0.5)
        print("======================================")
        time.sleep(0.5)
        print()
        print()
        time.sleep(0.5)            
        print("         1. Coffee Order ")
        time.sleep(0.5)
        print("         2. Admin Panel ")
        time.sleep(0.5)
        print("         3. Exit ")
        time.sleep(0.5)
        print()
        print()
        time.sleep(0.5)
        print("======================================")
        time.sleep(0.05)
        n=int(input("\n Enter your choice : "))
        if n==1:
                coffee_list()
        elif n==2:
                displaymenu()
        elif n==3:
                quit()
        else:
                print("\n Enter valid choice : ")
                time.sleep(0.5)
        print("======================================")
                

#-------------------------- coffee order menu  ------------------------
def coffee_list():
        clear()
        print()
        print("======================================")
        time.sleep(0.5)
        print("         Coffee Selections            ")
        time.sleep(0.5)
        print("======================================")
        time.sleep(0.5)
        df=pd.read_csv("coffee.csv",index_col=0)
        print(df)
        print()
        order()   
   
def order():
        print("======================================")
        time.sleep(0.5)
        print("            Your order                ")
        time.sleep(0.5)
        print("======================================")
        time.sleep(0.5)
        df=pd.read_csv("coffee.csv")
        time.sleep(0.5)
        c=input("\n Enter Customer Name : ")
        i=int(input("\n Enter Item No : "))
        q=int(input("\n Enter Item Quantity : "))
        n=df.iloc[i-1]["Item Name"]
        p=df.iloc[i-1]["Price"]
        print()
        clear()
        print("--------------------------------------")                 
        print("\n  1. Cash ") 
        print("\n  2. Card ")
        print()
        print("--------------------------------------")
        pay=int(input("\n Enter Payment Method  : "))
        print("======================================")
        bill=q*p
 #----------------------------- cash payment method code -------------------------------       
        if(pay==1):
                clear()
                time.sleep(2.0)
                print()
                print("======================================")
                print("               Bill                   ")
                print("======================================")
                print("\tCustomer Name :",c)
                print("\tItem Name     :",n)
                print("\tItem Ouantity :",q)
                print("\tItem Price    :",p)
                print("--------------------------------------")
                print("\tTotal         :",bill)
                print("--------------------------------------")
                time.sleep(8.0)
                clear()
                print("\n")
                print("\n")
                print("\n")
                print("\n")
                print("\n")
                print("\t\t\t\t\t    Thank You and Visit again....  ")
                time.sleep(3.0)
                clear()
                print("======================================")
                print()
                time.sleep(0.5)
                print(" 1. Buy Another Delicious ? ")
                time.sleep(0.5)
                print(" 2. Main Menu")
                print()
                time.sleep(0.5)
                print("======================================")
                ch=input("\n Enter choice : ")
                if(ch==1):   
                    order()
                else:
                    menu()    
               
               
 #-------------------------- card payment method code -------------------------------------  

        elif(pay==2):
                clear()
                print("======================================")
                time.sleep(0.5)
                card=int(input("\n Enter Card Number : "))
                pin=int(input("\n Enter PIN : "))
                print()
                clear()
                time.sleep(2.0)
                print()
                print("======================================")
                print("               Bill                   ")
                print("======================================")
                print("\tCustomer Name :",c)
                print("\tCard Number   :",card)
                print("\tItem Name     :",n)
                print("\tItem Ouantity :",q)
                print("\tItem Price    :",p)
                print("--------------------------------------")
                print("\tTotal         :",bill)
                print("--------------------------------------")
                time.sleep(2.0)
                clear()
                print("\n")
                print("\n")
                print("\n")
                print("\n")
                print("\n")
                print("\t\t\t\t\t    Thank You and Visit again....  ")
                time.sleep(3.0)
                clear()
                print("======================================")
                print()
                time.sleep(0.5)
                print(" 1. Buy Another Delicious ? ")
                time.sleep(0.5)
                print(" 2. Main Menu")
                print()
                time.sleep(0.5)
                print("======================================")
                ch=input("\n Enter choice : ")
                if(ch==1):   
                    order()
                else:
                    menu()    

#---------------------- Admin Panel login ------------------------------

def displaymenu():
        clear()
        print("\n")
        status=input("t\t\t\t\t You have ID and Password (y/n) ? :")
        if status=="y":
                login()
        elif status=="n":
                menu()
                
def login():
        login=input("\n\n\t\t\t\t\t Enter login name : ")
        password=input("\n\n\t\t\t\t\t Enter password : ")

        if(login=="csk" and password=="1224"):
                clear()
                print("\n")
                print("\n")
                print("\n")
                print("\n")
                print("\n")
                print("\t\t\t\t\t Login successfull....")
                time.sleep(1.0)
                admin_menu()
        else:
                print()
                time.sleep(1.0)
                print("\t\t\t\t\t Login not successfull !!!! ")
                print()
#--------------------------------- Admin panel ---------------------------------------
def admin_menu():
        clear()
        time.sleep(1.0)
        print("=======================================")
        time.sleep(0.5)
        print("         Welcome to Admin Panel        ")
        time.sleep(0.5)
        print("=======================================")
        time.sleep(0.5) 
        print()
        print()
        time.sleep(0.5)            
        print("         1. Add Item ")
        time.sleep(0.5)
        print("         2. Delete Item ")
        time.sleep(0.5)
        print("         3. Update Item List  ")
        time.sleep(0.5)
        print("         4. Display items  ")
        time.sleep(0.5)
        print("         5. Back to Menu ")
        time.sleep(0.5)
        print("         6. Exit ")
        time.sleep(0.5)
        print()
        print()
        time.sleep(0.5)
        print("======================================")
        time.sleep(0.5)
        n=int(input("\nEnter your Choice : "))
        if n==1:
                add_item()
        elif n==2:
                delete_item()
        elif n==3:
                update_item()
        elif n==4:
                stock()
        elif n==5:
                menu()
        elif n==6:
                quit()
        else:
                print("\nEnter valid choice : ")
                time.sleep(0.5)
        print("======================================")
#----------------------------------- code for display items -----------------------------
def stock():
        clear()
        print("=======================================")
        time.sleep(0.5)
        print("             Display Items             ")
        time.sleep(0.5)
        print("=======================================")
        time.sleep(0.5)    
        df=pd.read_csv("coffee.csv",index_col=0)
        print(df)
        time.sleep(0.5)
        print("=======================================")
        print(" 1. Go Back")
        print(" 2. Main Menu")
        print(" 3. Exit")
        print()
        print("=======================================")
        time.sleep(0.5)
        ch=int(input("\n Enter choice : "))
        if(ch==1):
                admin_menu()
        elif(ch==2):
                menu()
        elif(ch==3):
                quit()
#----------------------------- code for add item ---------------------------------
def add_item():
        clear()
        print("=======================================")
        time.sleep(0.5)
        print("               Add Item                ")
        time.sleep(0.5)
        print("=======================================")
        time.sleep(0.5)
        print()
        print() 
        time.sleep(0.5) 
        df=pd.read_csv("coffee.csv",index_col=0)
        #print(df)
        time.sleep(0.5)
        a=int(input("\n Enter Item Code : "))
        b=input("\n Enter Item Name : ")
        c=float(input("\n Enter Price : "))
        df.loc[a]=[b,c]
        print()
        clear()
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        for i in range(101):
                time.sleep(0.02)
                sys.stdout.write("\r\t\t\t\t\t %d %% Item adding......" % i)
                sys.stdout.flush()
        time.sleep(0.5)
        clear()
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\t\t\t\t\t Item Added successfully ......")
        time.sleep(3.0)
        clear()
        df.to_csv("coffee.csv")                                            #to save permanent
        time.sleep(0.5)
        print("====================================== ")
        time.sleep(0.5)
        print("        Coffee Selections              ") 
        print("=======================================")
        time.sleep(0.5)
        print(df)
        time.sleep(0.5)
        print("=======================================")
        print()
        time.sleep(0.5)
        print(" 1. Add Another Item")
        time.sleep(0.5)
        print(" 2. Go Back")
        time.sleep(0.5)
        print(" 3. Main Menu")
        time.sleep(0.5)
        print(" 0. Exit")
        print()
        print("=======================================")
        time.sleep(0.5)
        ch=int(input("\n Enter your choice : "))
        if(ch==1):
        	add_item()
        elif(ch==2):
                admin_menu()
        elif(ch==3):
                menu()
        elif(ch==0):
                quit()

#-----------------------------  code for delete item   -----------------------------
def delete_item():
        clear()
        print("=======================================")
        time.sleep(0.5)
        print("              Delete Item              ")
        time.sleep(0.5)
        print("=======================================") 
        time.sleep(0.5)
        print() 
        time.sleep(0.5) 
        df=pd.read_csv("coffee.csv",index_col=0)
        print(df)
        time.sleep(0.5)
        print("=======================================")
        time.sleep(0.5)
        code=int(input("\nEnter Item Code : "))
        df.drop(code,axis=0,inplace=True)
        clear()
        time.sleep(0.5)
        clear()
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\t\t\t\t\t Item Deleted successfully ......")
        time.sleep(2.0)
        clear()
        df.to_csv("coffee.csv")                                                #to delete permanent
        time.sleep(0.5)
        print("====================================== ")
        time.sleep(0.5)
        print("        Coffee Selections              ") 
        print("=======================================")
        time.sleep(0.5)
        print(df)
        time.sleep(0.5)
        print("=======================================")
        print()
        time.sleep(0.5)
        print()
        print(" 1. Delete Another Item")
        time.sleep(0.5)
        print(" 2. Go Back")
        time.sleep(0.5)
        print(" 3. Main Menu")
        time.sleep(0.5)
        print(" 4. Exit")
        print()
        time.sleep(0.5)
        print("=======================================")
        time.sleep(0.5)
        ch=int(input("\n Enter your choice : "))
        if(ch==1):
        	delete_item()
        elif(ch==2):
                admin_menu()
        elif(ch==3):
                menu()
        elif(ch==4):
                quit()
                                                                
#-------------------------------- code for update item ---------------------------------
def update_item():
        clear()
        print("======================================")
        time.sleep(0.5)
        print("             Update Item             ")
        time.sleep(0.5)
        print("======================================")
        df=pd.read_csv("coffee.csv",index_col=0)
        time.sleep(0.5)
        print(df)
        time.sleep(0.5)
        print("=======================================")
        time.sleep(0.5)
        print()
        print()
        time.sleep(0.5)
        a=int(input("\n Enter Item No. : "))
        b=input("\n Enter Item Name : ")
        c=float(input("\n Enter Price : "))
        df.loc[a]=[b,c]
        print()
        time.sleep(0.5)
        print()
        time.sleep(0.5)
        print("=======================================")
        clear()
        time.sleep(0.5)
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        for i in range(101):
                time.sleep(0.02)
                sys.stdout.write("\r\t\t\t\t\t %d %% Data Updated successfully" % i)
                sys.stdout.flush()       
        time.sleep(0.05)
        df.to_csv("coffee.csv") 
        clear()                                             
        print("======================================")
        time.sleep(0.5)
        print("             Updated List             ")
        time.sleep(0.5)
        print("======================================")
        time.sleep(0.5)
        print(df)
        time.sleep(0.5)
        print("=======================================")
        time.sleep(0.5)
        print()
        print("1. Update Another Item")
        time.sleep(0.5)
        print("2. Go Back")
        time.sleep(0.5)
        print("3. Main Menu")
        time.sleep(0.5)
        print("0. Exit")
        print()
        time.sleep(0.5)
        print("=======================================")
        time.sleep(0.5)
        ch=int(input("\nEnter choice : "))
        if(ch==1):
        	update_item()
        elif(ch==2):
                admin_menu()
        elif(ch==3):
                menu()
        elif(ch==0):
                quit()   

menu()
